name: Build on Tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: ClangKernel
      with:
        arch: arm64
        compiler: clang/14
        KERNEL_PATH: kernel-source
        defconfig: vendor/m23xq_eur_open_defconfig
        image: Image

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          name: "Kernel For Galaxy M23"
          files: |
            $GITHUB_WORKSPACE/kernel-source/out/arch/arm64/boot/*
            ${{ env.ZIP_NAME }}.zip
          tag_name: Galaxy_M23
